version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:  
      -  /api:/docker-entrypoint-initdb.d
    restart: always
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - ENVIRONMENT=prod
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
  # streamlit:
  #   build:
  #     context: ./streamlit
  #     dockerfile: Dockerfile
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=password
  #     - ENVIRONMENT=prod
  #     - POSTGRES_HOST=db
  #     - POSTGRES_PORT=5432
  #   ports:
  #     - "8501:8501"
  #   depends_on:
  #     - api
  #   restart: always